[default]
description = "Default permissions for the plugin"
permissions = ["allow-ping", "allow-create-file", "allow-read-file", "allow-write-file", "allow-append-to-file", "allow-delete-file", "allow-create-dir", "allow-list-dir", "allow-delete-dir", "allow-rename-dir"]
